language: scala

scala:
  - 2.10.4

branches:
  only:
    - master

env:
  global:
    secure: "OeVR1i1OiBQznAbYcJF3gCSAFf3ILZB6tGbW5qePXggZNSYZvGmReAWuG6lN79Ktz3Tivelr/rkoEm2Q7gzJO3PJ/z0tnufe76aVYVv1igts43YdDQ3bGylC2bPxLG/RgsVZGmqNWaT7+10wmdrYvhUNb7H/krnLRPDu6eQQAe0="

before_script:
  - git config --global user.email "z@zman.io"
  - git config --global user.name "zmanio-ci"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  
script: "sbt test ghpages-push-site"

notifications:
  email:
    - z@zman.io
