language: scala

scala:
  - 2.10.4

branches:
  only:
    - master

env:
  global:
    secure: "OeVR1i1OiBQznAbYcJF3gCSAFf3ILZB6tGbW5qePXggZNSYZvGmReAWuG6lN79Ktz3Tivelr/rkoEm2Q7gzJO3PJ/z0tnufe76aVYVv1igts43YdDQ3bGylC2bPxLG/RgsVZGmqNWaT7+10wmdrYvhUNb7H/krnLRPDu6eQQAe0="

before_script:
  - git config --global user.email "z@zman.io"
  - git config --global user.name "zmanio-ci"
  - git config --global push.default simple
  
script: sbt ++$TRAVIS_SCALA_VERSION --warn test ghpages-push-site

notifications:
  email:
    - z@zman.io
